## Student Mark Analyzer

In [1]:
import pandas as pd
import numpy as np

#Creating data and saving into CSV
data = {

    "Name of student": [ "Ayesha", "Ali", "Amna", "Subhan", "Tabish", "Fatima", "Eliyah", "Eshal", "Shahroz","Shahrif",
        "Sara", "Sana", "Ayan", "Kainat", "Iqra", "Areeba", "Hamza", "Hina", "Bilal","Ayesha","Bilal","Anaya","Saba", 
                        "Sobia","Anaya","Abdullah", "Kamran", "Talha", "Zayam", "Shehzad" ],
    
    "Computer":[ 78, 85, 90, np.nan, 67, 56, 44, 93, 150, 81,74, 60, 35, 49, 71, 89, 95, 63, -5,78,          
        -5, 84, np.nan, 52,84,79, 88, 72, 65, 91 ],

    "English": [ 80, 72, 95, 88, 76, np.nan, 58, 91, 69, 84,73, 65, 40, 53, 72, 91, 86, 61, 57,80,          
        57,82, 75, np.nan, 82,77, 89, 70, 68, 92 ],

    "Maths": [ 75, 82, 91, 85, np.nan, 61, 51, 90, 73, 80, 69, 67, 38, 50, 75, 88, 93, 65, 56,75,
              56,85,79, 48, 85, 80, 87, 74, 66, 105],

    "Programming": [ 83, 91, 94, 87, 71, 66, 49, np.nan, 78, 86, 74, 68, 39, 51, 77, 92, 94, 62, 58,
        83,58,86, 81, 49, 86,82, 90, 76, 67, -20 ],

    "Discrete": [ 79, 84, 93, 86, 69, 63, 48, 90, 76, 83,72, 64, 36, 47, 74, 90, 95, np.nan, 55,
        79,55,83, 78, 50, 83,81, 89, 75, 69, 88 ]
}
df = pd.DataFrame(data)
df.to_csv("Student Marks.csv", index=False)
print("CSV file of student marks is created successfully")

CSV file of student marks is created successfully

In [2]:
df = pd.read_csv("Student Marks.csv")
display(df)

   Name of student  Computer  English  Maths  Programming  Discrete
0           Ayesha      78.0     80.0   75.0         83.0      79.0
1              Ali      85.0     72.0   82.0         91.0      84.0
2             Amna      90.0     95.0   91.0         94.0      93.0
3           Subhan       NaN     88.0   85.0         87.0      86.0
4           Tabish      67.0     76.0    NaN         71.0      69.0
5           Fatima      56.0      NaN   61.0         66.0      63.0
6           Eliyah      44.0     58.0   51.0         49.0      48.0
7            Eshal      93.0     91.0   90.0          NaN      90.0
8          Shahroz     150.0     69.0   73.0         78.0      76.0
9          Shahrif      81.0     84.0   80.0         86.0      83.0
10            Sara      74.0     73.0   69.0         74.0      72.0
11            Sana      60.0     65.0   67.0         68.0      64.0
12            Ayan      35.0     40.0   38.0         39.0      36.0
13          Kainat      49.0     53.0   50.0         51.0      47.0
14            Iqra      71.0     72.0   75.0         77.0      74.0
15          Areeba      89.0     91.0   88.0         92.0      90.0
16           Hamza      95.0     86.0   93.0         94.0      95.0
17            Hina      63.0     61.0   65.0         62.0       NaN
18           Bilal      -5.0     57.0   56.0         58.0      55.0
19          Ayesha      78.0     80.0   75.0         83.0      79.0
20           Bilal      -5.0     57.0   56.0         58.0      55.0
21           Anaya      84.0     82.0   85.0         86.0      83.0
22            Saba       NaN     75.0   79.0         81.0      78.0
23           Sobia      52.0      NaN   48.0         49.0      50.0
24           Anaya      84.0     82.0   85.0         86.0      83.0
25        Abdullah      79.0     77.0   80.0         82.0      81.0
26          Kamran      88.0     89.0   87.0         90.0      89.0
27           Talha      72.0     70.0   74.0         76.0      75.0
28           Zayam      65.0     68.0   66.0         67.0      69.0
29         Shehzad      91.0     92.0  105.0        -20.0      88.0

In [3]:
# Count missing values 
print(df.isnull().sum())

Name of student    0
Computer           2
English            2
Maths              1
Programming        1
Discrete           1
dtype: int64

In [4]:
# Checking duplicate rows
print(df.duplicated())
print("Total duplicate rows:", df.duplicated().sum())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
21    False
22    False
23    False
24     True
25    False
26    False
27    False
28    False
29    False
dtype: bool
Total duplicate rows: 3

In [5]:
df = df.drop_duplicates()
print(df.duplicated().sum())

0

In [6]:
# Replace marks greater than 100 or less than 0 with subject average

subjects = ["Computer", "English", "Maths", "Programming", "Discrete"]
for subject in subjects:
    average = df[(df[subject] >= 0) & (df[subject] <= 100)][subject].mean()
    invalid = df[(df[subject] > 100) | (df[subject] < 0)]
    
    if len(invalid) > 0:
        print("Fixed invalid marks in", subject, "replaced with average", round(average, 2))
    
    df.loc[df[subject] > 100, subject] = average
    df.loc[df[subject] < 0, subject] = average

display(df)

Fixed invalid marks in Computer replaced with average 72.22
Fixed invalid marks in Maths replaced with average 72.32
Fixed invalid marks in Programming replaced with average 74.04

   Name of student   Computer  English  Maths  Programming  Discrete
0           Ayesha  78.000000     80.0  75.00        83.00      79.0
1              Ali  85.000000     72.0  82.00        91.00      84.0
2             Amna  90.000000     95.0  91.00        94.00      93.0
3           Subhan        NaN     88.0  85.00        87.00      86.0
4           Tabish  67.000000     76.0    NaN        71.00      69.0
5           Fatima  56.000000      NaN  61.00        66.00      63.0
6           Eliyah  44.000000     58.0  51.00        49.00      48.0
7            Eshal  93.000000     91.0  90.00          NaN      90.0
8          Shahroz  72.217391     69.0  73.00        78.00      76.0
9          Shahrif  81.000000     84.0  80.00        86.00      83.0
10            Sara  74.000000     73.0  69.00        74.00      72.0
11            Sana  60.000000     65.0  67.00        68.00      64.0
12            Ayan  35.000000     40.0  38.00        39.00      36.0
13          Kainat  49.000000     53.0  50.00        51.00      47.0
14            Iqra  71.000000     72.0  75.00        77.00      74.0
15          Areeba  89.000000     91.0  88.00        92.00      90.0
16           Hamza  95.000000     86.0  93.00        94.00      95.0
17            Hina  63.000000     61.0  65.00        62.00       NaN
18           Bilal  72.217391     57.0  56.00        58.00      55.0
21           Anaya  84.000000     82.0  85.00        86.00      83.0
22            Saba        NaN     75.0  79.00        81.00      78.0
23           Sobia  52.000000      NaN  48.00        49.00      50.0
25        Abdullah  79.000000     77.0  80.00        82.00      81.0
26          Kamran  88.000000     89.0  87.00        90.00      89.0
27           Talha  72.000000     70.0  74.00        76.00      75.0
28           Zayam  65.000000     68.0  66.00        67.00      69.0
29         Shehzad  91.000000     92.0  72.32        74.04      88.0

In [7]:
#Filling missing value with subjects average
for subject in subjects:
    df[subject] = df[subject].fillna(round(df[subject].mean()))
display(df)

   Name of student   Computer  English  Maths  Programming  Discrete
0           Ayesha  78.000000     80.0  75.00        83.00      79.0
1              Ali  85.000000     72.0  82.00        91.00      84.0
2             Amna  90.000000     95.0  91.00        94.00      93.0
3           Subhan  72.000000     88.0  85.00        87.00      86.0
4           Tabish  67.000000     76.0  72.00        71.00      69.0
5           Fatima  56.000000     75.0  61.00        66.00      63.0
6           Eliyah  44.000000     58.0  51.00        49.00      48.0
7            Eshal  93.000000     91.0  90.00        74.00      90.0
8          Shahroz  72.217391     69.0  73.00        78.00      76.0
9          Shahrif  81.000000     84.0  80.00        86.00      83.0
10            Sara  74.000000     73.0  69.00        74.00      72.0
11            Sana  60.000000     65.0  67.00        68.00      64.0
12            Ayan  35.000000     40.0  38.00        39.00      36.0
13          Kainat  49.000000     53.0  50.00        51.00      47.0
14            Iqra  71.000000     72.0  75.00        77.00      74.0
15          Areeba  89.000000     91.0  88.00        92.00      90.0
16           Hamza  95.000000     86.0  93.00        94.00      95.0
17            Hina  63.000000     61.0  65.00        62.00      74.0
18           Bilal  72.217391     57.0  56.00        58.00      55.0
21           Anaya  84.000000     82.0  85.00        86.00      83.0
22            Saba  72.000000     75.0  79.00        81.00      78.0
23           Sobia  52.000000     75.0  48.00        49.00      50.0
25        Abdullah  79.000000     77.0  80.00        82.00      81.0
26          Kamran  88.000000     89.0  87.00        90.00      89.0
27           Talha  72.000000     70.0  74.00        76.00      75.0
28           Zayam  65.000000     68.0  66.00        67.00      69.0
29         Shehzad  91.000000     92.0  72.32        74.04      88.0

In [8]:
#Convert all subject columns to integers
for subject in subjects:
    df[subject] = df[subject].astype(int)

display(df)

   Name of student  Computer  English  Maths  Programming  Discrete
0           Ayesha        78       80     75           83        79
1              Ali        85       72     82           91        84
2             Amna        90       95     91           94        93
3           Subhan        72       88     85           87        86
4           Tabish        67       76     72           71        69
5           Fatima        56       75     61           66        63
6           Eliyah        44       58     51           49        48
7            Eshal        93       91     90           74        90
8          Shahroz        72       69     73           78        76
9          Shahrif        81       84     80           86        83
10            Sara        74       73     69           74        72
11            Sana        60       65     67           68        64
12            Ayan        35       40     38           39        36
13          Kainat        49       53     50           51        47
14            Iqra        71       72     75           77        74
15          Areeba        89       91     88           92        90
16           Hamza        95       86     93           94        95
17            Hina        63       61     65           62        74
18           Bilal        72       57     56           58        55
21           Anaya        84       82     85           86        83
22            Saba        72       75     79           81        78
23           Sobia        52       75     48           49        50
25        Abdullah        79       77     80           82        81
26          Kamran        88       89     87           90        89
27           Talha        72       70     74           76        75
28           Zayam        65       68     66           67        69
29         Shehzad        91       92     72           74        88

In [9]:
#Calculate Average Marks of Each Student
df["Average"] = ( df["Computer"] + df["English"] + df["Maths"] + df["Programming"] + df["Discrete"] ) / 5
display(df)

   Name of student  Computer  English  Maths  Programming  Discrete  Average
0           Ayesha        78       80     75           83        79     79.0
1              Ali        85       72     82           91        84     82.8
2             Amna        90       95     91           94        93     92.6
3           Subhan        72       88     85           87        86     83.6
4           Tabish        67       76     72           71        69     71.0
5           Fatima        56       75     61           66        63     64.2
6           Eliyah        44       58     51           49        48     50.0
7            Eshal        93       91     90           74        90     87.6
8          Shahroz        72       69     73           78        76     73.6
9          Shahrif        81       84     80           86        83     82.8
10            Sara        74       73     69           74        72     72.4
11            Sana        60       65     67           68        64     64.8
12            Ayan        35       40     38           39        36     37.6
13          Kainat        49       53     50           51        47     50.0
14            Iqra        71       72     75           77        74     73.8
15          Areeba        89       91     88           92        90     90.0
16           Hamza        95       86     93           94        95     92.6
17            Hina        63       61     65           62        74     65.0
18           Bilal        72       57     56           58        55     59.6
21           Anaya        84       82     85           86        83     84.0
22            Saba        72       75     79           81        78     77.0
23           Sobia        52       75     48           49        50     54.8
25        Abdullah        79       77     80           82        81     79.8
26          Kamran        88       89     87           90        89     88.6
27           Talha        72       70     74           76        75     73.4
28           Zayam        65       68     66           67        69     67.0
29         Shehzad        91       92     72           74        88     83.4

In [10]:
# Find the student with the highest average
highest = df[df["Average"] == df["Average"].max()]
print("Student with the highest average are:")
print(highest)
# Find the student with the lowest average
lowest = df[df["Average"] == df["Average"].min()]

print("Student With the lowest average is:")
print(lowest)

Student with the highest average are:
   Name of student  Computer  English  Maths  Programming  Discrete  Average
2             Amna        90       95     91           94        93     92.6
16           Hamza        95       86     93           94        95     92.6
Student With the lowest average is:
   Name of student  Computer  English  Maths  Programming  Discrete  Average
12            Ayan        35       40     38           39        36     37.6

In [11]:
# Mean of every subject
print("Mean")
for subject in subjects:
    print(subject, "=", np.mean(df[subject]))
    
# Median 
print("Median")
for subject in subjects:
    print(subject, "=", np.median(df[subject]))

# Standard deviation 

print("Standard Deviation")
for subject in subjects:
    print(subject, "=", np.std(df[subject]))

Mean
Computer = 72.18518518518519
English = 74.5925925925926
Maths = 72.29629629629629
Programming = 74.03703703703704
Discrete = 73.74074074074075
Median
Computer = 72.0
English = 75.0
Maths = 74.0
Programming = 76.0
Discrete = 76.0
Standard Deviation
Computer = 15.29956919518648
English = 13.041981385650297
Maths = 14.136411653270677
Programming = 14.796099289468607
Discrete = 15.269414096772362

In [12]:
# Add Pass/Fail column
df["Result"] = np.where(df["Average"] >= 40, "Pass", "Fail")
display(df)

,Name of student,Computer,English,Maths,Programming,Discrete,Average,Result
0,Ayesha,78,80,75,83,79,79.0,Pass
1,Ali,85,72,82,91,84,82.8,Pass
2,Amna,90,95,91,94,93,92.6,Pass
3,Subhan,72,88,85,87,86,83.6,Pass
4,Tabish,67,76,72,71,69,71.0,Pass
5,Fatima,56,75,61,66,63,64.2,Pass
6,Eliyah,44,58,51,49,48,50.0,Pass
7,Eshal,93,91,90,74,90,87.6,Pass
8,Shahroz,72,69,73,78,76,73.6,Pass
9,Shahrif,81,84,80,86,83,82.8,Pass
10,Sara,74,73,69,74,72,72.4,Pass
11,Sana,60,65,67,68,64,64.8,Pass
12,Ayan,35,40,38,39,36,37.6,Fail
13,Kainat,49,53,50,51,47,50.0,Pass
14,Iqra,71,72,75,77,74,73.8,Pass
15,Areeba,89,91,88,92,90,90.0,Pass
16,Hamza,95,86,93,94,95,92.6,Pass
17,Hina,63,61,65,62,74,65.0,Pass
18,Bilal,72,57,56,58,55,59.6,Pass
21,Anaya,84,82,85,86,83,84.0,Pass
22,Saba,72,75,79,81,78,77.0,Pass
23,Sobia,52,75,48,49,50,54.8,Pass
25,Abdullah,79,77,80,82,81,79.8,Pass
26,Kamran,88,89,87,90,89,88.6,Pass
27,Talha,72,70,74,76,75,73.4,Pass
28,Zayam,65,68,66,67,69,67.0,Pass
29,Shehzad,91,92,72,74,88,83.4,Pass

In [13]:
print("Total Students =", len(df))

passed = len(df[df["Result"] == "Pass"])
print("Passed Students =", passed)

failed = len(df[df["Result"] == "Fail"])
print("Failed Students =", failed)

print("Subject wise Class Average")
for subject in subjects:
    print(subject, "=", round(df[subject].mean(), 2))

Total Students = 27
Passed Students = 26
Failed Students = 1
Subject wise Class Average
Computer = 72.19
English = 74.59
Maths = 72.3
Programming = 74.04
Discrete = 73.74

In [14]:
df = df.sort_values(by="Average", ascending=False)
print("Students Sorted by Average Marks")
display(df)

Students Sorted by Average Marks

,Name of student,Computer,English,Maths,Programming,Discrete,Average,Result
2,Amna,90,95,91,94,93,92.6,Pass
16,Hamza,95,86,93,94,95,92.6,Pass
15,Areeba,89,91,88,92,90,90.0,Pass
26,Kamran,88,89,87,90,89,88.6,Pass
7,Eshal,93,91,90,74,90,87.6,Pass
21,Anaya,84,82,85,86,83,84.0,Pass
3,Subhan,72,88,85,87,86,83.6,Pass
29,Shehzad,91,92,72,74,88,83.4,Pass
1,Ali,85,72,82,91,84,82.8,Pass
9,Shahrif,81,84,80,86,83,82.8,Pass
25,Abdullah,79,77,80,82,81,79.8,Pass
0,Ayesha,78,80,75,83,79,79.0,Pass
22,Saba,72,75,79,81,78,77.0,Pass
14,Iqra,71,72,75,77,74,73.8,Pass
8,Shahroz,72,69,73,78,76,73.6,Pass
27,Talha,72,70,74,76,75,73.4,Pass
10,Sara,74,73,69,74,72,72.4,Pass
4,Tabish,67,76,72,71,69,71.0,Pass
28,Zayam,65,68,66,67,69,67.0,Pass
17,Hina,63,61,65,62,74,65.0,Pass
11,Sana,60,65,67,68,64,64.8,Pass
5,Fatima,56,75,61,66,63,64.2,Pass
18,Bilal,72,57,56,58,55,59.6,Pass
23,Sobia,52,75,48,49,50,54.8,Pass
6,Eliyah,44,58,51,49,48,50.0,Pass
13,Kainat,49,53,50,51,47,50.0,Pass
12,Ayan,35,40,38,39,36,37.6,Fail